MYSQL_ESTATE_HOST="10.104.0.5"
MYSQL_ESTATE_PORT=3306
MYSQL_ESTATE_USER=isucon
MYSQL_ESTATE_DBNAME=isuumo
MYSQL_ESTATE_PASS=isucon

MYSQL_CHAIR_HOST="10.104.0.2"
MYSQL_CHAIR_PORT=3306
MYSQL_CHAIR_USER=isucon
MYSQL_CHAIR_DBNAME=isuumo
MYSQL_CHAIR_PASS=isucon

GOGC=6000